---
rvm: 2.1
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test
  - cat .kitchen/logs/default-ubuntu-1404.log
