  ---
- name: Directory Exists | /etc/ansible
  file:
    state: directory
    path: /etc/ansible
    owner: root
    group: staff
    mode: 0775
  tags:
    - directory-structure
    - configuration
    - ansible

- name: Upload Config | Ansible | Hosts
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: staff
    mode: 0664
  with_items:
    - etc/ansible/hosts 
    - etc/ansible/ansible.cfg
  tags:
    - template-configuration
    - configuration
    - ansible
